<div class="gel-wrap">
    <div class="gel-layout">
        <div class="gel-layout__item gel-1/1">
            <h1>Developer Scaffold</h1>
            <h2>Bespoke markup, not componentised</h2>
            <div class="tmpShareToolsHolder">Loading sharetools...</div>
        </div>
        <div class="gel-layout__item gel-1/2 gel-1/4@m">Column 1 (gel layout)</div>
        <div class="gel-layout__item gel-1/2 gel-1/4@m">Column 2</div>
        <div class="gel-layout__item gel-1/2 gel-1/4@m">Another column 1</div>
        <div class="gel-layout__item gel-1/2 gel-1/4@m">Another column 2</div>
    </div>
</div>
